/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeBlockComponent: typeof import('./src/components/CodeBlockComponent.vue')['default']
    CommandsList: typeof import('./src/components/extensions/components/slashCommands/CommandsList.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Group: typeof import('./src/components/Toolbar/Group.vue')['default']
    Index: typeof import('./src/components/Toolbar/Index.vue')['default']
    LinkDialog: typeof import('./src/components/extensions/components/LinkDialog.vue')['default']
    MenuBubble: typeof import('./src/components/MenuBubble.vue')['default']
    MenuFloating: typeof import('./src/components/MenuFloating.vue')['default']
    ShowSource: typeof import('./src/components/extensions/components/ShowSource.vue')['default']
    Tiptapify: typeof import('./src/components/Tiptapify.vue')['default']
    Toggle: typeof import('./src/components/Toolbar/Toggle.vue')['default']
  }
}
