/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BtnIcon: typeof import('./src/components/UI/BtnIcon.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Index: typeof import('./src/components/Toolbar/Index.vue')['default']
    Items: typeof import('./src/components/Toolbar/Items.vue')['default']
    MenuBubble: typeof import('./src/components/MenuBubble.vue')['default']
    MenuFloating: typeof import('./src/components/MenuFloating.vue')['default']
    Tiptapify: typeof import('./src/components/Tiptapify.vue')['default']
    TiptapifyDialog: typeof import('./src/components/UI/TiptapifyDialog.vue')['default']
  }
}
